require 'config.options'
require 'config.keymaps'
require 'config.autocmds'
require 'config.pack'

require 'plugins.colorscheme'
require 'plugins.ui'
require 'plugins.oil'
require 'plugins.telescope'
require 'plugins.lsp'
require 'plugins.rustaceanvim'
require 'plugins.format'
require 'plugins.completion'
require 'plugins.treesitter'
require 'plugins.markdown'
require 'plugins.diffview'
require 'plugins.dap'
require 'plugins.neotest'
require 'plugins.flash'
require 'plugins.trouble'
require 'plugins.bufferline'
require 'plugins.highlight-colors'

-- vim: ts=2 sts=2 sw=2 et
